name: Run Unit Tests with GTest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Instalar dependências necessárias
      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install cmake g++ -y

      # Baixar e configurar o vcpkg
      - name: Download and set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg install gtest
          cd ..

      # Configurar o CMake com o toolchain do vcpkg
      - name: Configure CMake with vcpkg toolchain
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake

      # Compilar o projeto e os testes
      - name: Build project and tests
        run: |
          cd build
          make

      # Executar os testes unitários
      - name: Run unit tests
        run: |
          cd build
          ctest --output-on-failure
